name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Build project
      run: |
        if npm run | grep -q 'build'; then
          npm run build
        else
          echo "No build script found. Skipping build."
        fi

    - name: Run tests
      run: |
        if npm run | grep -q 'test'; then
          npm test
        else
          echo "No test script found. Skipping tests."
        fi
