name: SonarQube analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read  # Allows SonarQube to decorate PRs with analysis results

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SonarQube Scanner
        uses: SonarSource/sonarqube-scan-action@7295e71c9583053f5bf40e9d4068a0c974603ec8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     # Auto-provided by GitHub Actions
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}       # Your SonarQube token secret
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # Your SonarQube instance URL secret
        with:
          args: >
            -Dsonar.projectKey=your_project_key_here
            # Optional: specify source folder if different than root
            # -Dsonar.sources=src
            # Optional: enable verbose logs for debugging
            # -Dsonar.verbose=true
